# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.2.6 # This is the action
      with:
        heroku_api_key: "5c9c00c3-fa3f-4b11-b06a-7a74c098f40d" #${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "helpharmafrontend" #Must be unique in Heroku
        heroku_email: "mavalderrama@outlook.com"
        usedocker: true
        appdir: "frontend"
