# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
      id: heroku
      uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
      with:
        email: "mavalderrama@outlook.com" # your heroku email
        api_key: "5c9c00c3-fa3f-4b11-b06a-7a74c098f40d" # your  heroku api key
        docker_compose_file: './docker-compose.yml' # set the path to the folder where the docker-compose file is located
        heroku_apps: '[{"imagename":"helpharma_pharma_hell","appname":"hellpharmafront","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type
